version: '3.9'
services:
  nuxt-chat:
    build: .
    container_name: nuxt3-chat-ui
    ports:
      - '3000:3000'
    environment:
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3000
      GIGACHAT_ENDPOINT: ${GIGACHAT_ENDPOINT:-/api/chat}
      LM_MODELS_ENDPOINT: ${LM_MODELS_ENDPOINT:-/V1/models}
    restart: unless-stopped
