version: '3.9'
services:
  nuxt-chat:
    build: .
    container_name: nuxt3-chat-ui
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3000
    restart: unless-stopped
